version: "3.7"

services:
  #set nama service item-app
  item-app:
    #get image dari docker smamhtn/item-app:v1
    image: ghcr.io/smam-tech/dbsfcc-devops-expert-2023:v1
    #set port 8080 container to port 80 host
    ports:
      - 80:8080
    container_name: item-app
    #memastikan run setelah item-db di run
    depends_on:
      item-db:
       condition: service_healthy
    #melakukan restart bila gagal
    restart: on-failure
  #set nama service item-db
  item-db:
    #get image mongo:3
    image: mongo:3
    #set volumes app-db ke /data/db
    volumes:
      - app-db:/data/db
    container_name: item-db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats().ok"]
      interval: 30s
      timeout: 10s
      retries: 5
    
#set volume dengan nama app-db
volumes:
  app-db: